#define AvVersion                  "20220630"
#define GSV2K11                    1
#define Gsv2k11MuxMode             0
#define Gsv2k11AudioBypass         0
#define Gsv2kResourceSize          (Gsv2k11ResourceSize)*(GSV2K11)
#define AvEnableVideoLogicBus      1
#define AvForceDefaultEdid         0
#define AvStrictEdidRule           1
#define AvEdidMaxSize              256
#define AvEnableCecFeature         0
#define AvCecLinkageMode           1
#define AvCecMessageEvent          AvEnableCecFeature
#define AvCecDataReadingInEvent    AvEnableCecFeature
#define AvCecDataSendingOutEvent   AvEnableCecFeature
#define AvCecGsvVendorIdByte1      0xa5
#define AvCecGsvVendorIdByte2      0xa5
#define AvCecGsvVendorIdByte3      0xa5
#define AvCecLogicAddress          0x5
#define AvEnableAudioTTLInput      1
#define AvEnableInternalVideoGen   1
#define AvEnableInternalAudioGen   0
#define AvEnableInternalClockGen   0
#define AvEnableHdcp2p2Feature     1
#define AvEnableSimplifyHdcp       1
#define AvEnableUartInput          0
#define AvEnableDebugMessage       1
#define AvEnableDebugHdcp          0
#define AvEnableDebugFsm           1
#define AvEnableIntegrityCheck     0
#define AvEnableKeyInput           1
#define AvKeyDelayThreshold        250
#define AvIrdaFunctionInput        0
#define RxHpdDelayExpireThreshold  15
#define RxLockDelayExpireThreshold 1
#define RxEQDelayExpireThreshold   2
#define TxVideoManageThreshold     5
#define TxHdcpManageThreshold      50
#define AvDontCareEdidSpa          1
#define AvNoLinkageMode            1
#define AvAllowHpdLowEdidRead      0
#define AvEnableDetailTiming       1
#define AvHdcpRxErrorThreshold     10
#define AvHdcpTxErrorThreshold     5
#define AvEdidStoredInRam          0
#define AvEdidSameNoAcknowledge    1
#define AvEdidErrorThreshold       10
#define AvEnableHdcp1p4BksvCheck   0
#define AvEnableTxScdcCedCheck     0
#define AvEnableTxCtsPhySetting    0
#define Gsv2k11LaneCompensation    1
#define Gsv2k11WeakParallelDrive   0
#define Gsv2k11I2SBitAlignment     0
